### ISSUE TITLE
Metadata version mismatch for module /home/opr/ui/node_modules/angular-datatables/index.d.ts

### ISSUE THREAD

**Issue by kalimalrazif** [l-lin/angular-datatables#1185]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What versions you are using?

<pre><code>
- node version:
- angular version:
- angular-cli version:X
- jquery version:
- datatables version:
- angular-datatables version:
</code></pre>

## Current behavior

I followed the steps on https://l-lin.github.io/angular-datatables/#/getting-started and when I start the thing with ng serve, shows this:

ERROR in Error: Metadata version mismatch for module /home/opr/ui/node_modules/angular-datatables/index.d.ts, found version 4, expected 3, resolving symbol AppModule in /home/opr/ui/src/app/app.module.ts, resolving symbol AppModule in /home/opr/ui/src/app/app.module.ts
    at Error (native)
    at syntaxError (/home/opr/ui/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/home/opr/ui/node_modules/@angular/compiler/bundles/compiler.umd.js:25118:23)
    at StaticReflector.simplify (/home/opr/ui/node_modules/@angular/compiler/bundles/compiler.umd.js:25130:13)
    at StaticReflector.annotations (/home/opr/ui/node_modules/@angular/compiler/bundles/compiler.umd.js:24558:41)
    at _getNgModuleMetadata (/home/opr/ui/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/opr/ui/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/home/opr/ui/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/opr/ui/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/opr/ui/node_modules/@ngtools/webpack/src/plugin.js:210:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/opr/ui/node_modules/@ngtools/webpack/src/plugin.js:446:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by LGCrhys** [comment]
Same here.

    "@angular/cli": "^1.7.1",
    "angular-datatables": "^5.0.0",
    "datatables.net": "^1.10.16",
    "datatables.net-dt": "^1.10.16",
    "jquery": "^3.3.1",

**Comment by l-lin** [comment]
Check this [answer on stackoverflow](https://stackoverflow.com/a/47534611/3612053).
For reminder, angular-datatables major version follows the major version of Angular, which means angular-datatables version 5 is for Angular 5.

**Comment by LGCrhys** [comment]
Yep ! It works with angular-datatables : 4.4.1 ;-)

Or if i upgrade angular of course.

Thx!

**Comment by kalimalrazif** [comment]
it works! 
Had to upgrade several angular components but it works :-)

Thanks :-)
