### ISSUE TITLE
ng test is throwing error: $ is not defined

### ISSUE THREAD

**Issue by chr1soscl** [l-lin/angular-datatables#1432]
I am using the following dependencies
Dependencies:
```
"dependencies": {
    "@angular/animations": "^8.1.2",
    "@angular/cdk": "^8.1.1",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.1.2",
    "@angular/forms": "^8.0.0",
    "@angular/material": "^8.1.1",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/router": "^8.0.0",
    "@nrwl/angular": "^8.2.0",
    "angular-datatables": "^8.0.0",
    "bootstrap": "^4.3.1",
    "core-js": "^2.5.4",
    "datatables.net": "^1.10.20",
    "datatables.net-dt": "^1.10.20",
    "hammerjs": "^2.0.8",
    "jquery": "^3.4.1",
    "ngx-bootstrap": "^5.1.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "^0.9.1"
  },
```
Dev Dependencies:
```
"devDependencies": {
    "@angular-devkit/build-angular": "^0.800.0",
    "@angular/cli": "8.0.0",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/language-service": "^8.0.0",
    "@nrwl/cypress": "8.2.0",
    "@nrwl/jest": "8.2.0",
    "@nrwl/workspace": "8.2.0",
    "@types/datatables.net": "^1.10.18",
    "@types/jest": "24.0.9",
    "@types/jquery": "^3.3.31",
    "@types/node": "~8.9.4",
    "codelyzer": "~5.0.1",
    "cypress": "~3.3.1",
    "dotenv": "6.2.0",
    "jest": "24.1.0",
    "jest-junit": "^8.0.0",
    "jest-preset-angular": "7.0.0",
    "prettier": "1.16.4",
    "ts-jest": "24.0.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.4.5"
  },
"jest-junit": {
    "output": "coverage/junit/junit.xml",
    "usePathForSuiteName": "true"
  } 
```
when running any test that uses the component, I am getting this error:
```
ReferenceError: $ is not defined

      at ../../node_modules/angular-datatables/bundles/angular-datatables.umd.js:55:25
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:423:31)
      at AsyncTestZoneSpec.Object.<anonymous>.AsyncTestZoneSpec.onInvokeTask (../../node_modules/zone.js/dist/async-test.js:90:25)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (../../node_modules/zone.js/dist/proxy.js:157:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:422:60)
      at Object.onInvokeTask (../../../packages/core/src/zone/ng_zone.ts:262:25)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:422:60)
      at Zone.Object.<anonymous>.Zone.runTask (../../node_modules/zone.js/dist/zone.js:195:47)
      at Object.<anonymous>.ZoneTask.invokeTask (../../node_modules/zone.js/dist/zone.js:498:34)
      at ZoneTask.invoke (../../node_modules/zone.js/dist/zone.js:487:48)
      at timer (../../node_modules/zone.js/dist/zone.js:3070:29)
      at Timeout.callback [as _onTimeout] (../../node_modules/jsdom/lib/jsdom/browser/Window.js:678:19)
```
I already tried ordering the script imports as:
```
"scripts": [
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/datatables.net/js/jquery.dataTables.js"
            ]
```
Also tried defining the $ in the app.module.ts, in the table.component.ts and table.component.spect.ts:
`import * as $ from 'jquery'`
Also tried importing jquery in the index.html, but none is working, how can I define $ for the purpose of running ng test?

**Comment by shanmukhateja** [comment]
Hi,

This could be because of how Karma Angular's testing framework works. A quick Google search led me to this:

https://stackoverflow.com/questions/40013155/angular-2-and-jquery-how-to-test
