### ISSUE TITLE
hide() exception

### ISSUE THREAD

**Issue by narzul1** [l-lin/angular-datatables#205]
I added an angular-datatable to my project

<table id="drivers" datatable=" " dt-options=" teams.dtoptions" dt-column-defs="teams.dtColumnDefs" class="data hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Number of Driver</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="team in teams.Teams">
                <td>{{ team.Title }}</td>
                <td>{{ team.Description }}</td>
                <td>{{ team.Options }}</td>
                <td>
                    <button type="button" title="Edit Team" ng-click="teams.editTeam(team)" class="btn-default"><i class="fa fa-edit"></i></button>
                    <button type="button" title="Remove Team" ng-click="teams.removeTeam(team)" class="btn-default"><i class="fa fa-trash-o"></i></button>
                </td>
            </tr>
        </tbody>
    </table>

 but I get this error, would you know where it comes form ?

```
TypeError: Object doesn't support property or method 'hide'
   at showLoading (http://localhost:52445/Scripts/angular-datatables.renderer.js:33:9)
   at postLink (http://localhost:52445/Scripts/angular-datatables.directive.js:37:13)
   at Anonymous function (http://localhost:52445/Scripts/angular.js:7114:47)
   at nodeLinkFn (http://localhost:52445/Scripts/angular.js:6712:31)
   at compositeLinkFn (http://localhost:52445/Scripts/angular.js:6106:31)
   at compositeLinkFn (http://localhost:52445/Scripts/angular.js:6109:31)
   at publicLinkFn (http://localhost:52445/Scripts/angular.js:6002:44)
   at Anonymous function (http://localhost:52445/Scripts/angular-ui-router.min.js:7:26534)
   at nodeLinkFn (http://localhost:52445/Scripts/angular.js:6712:31)
   at compositeLinkFn (http://localhost:52445/Scripts/angular.js:6106:31)<table class="data hover ng-isolate-scope" id="drivers" dt-column-defs="teams.dtColumnDefs" dt-options=" teams.dtoptions" datatable=" "> 
```

Thanks

**Comment by l-lin** [comment]
You must include the JS file in this order: 
* `jQuery`
* `DataTables`
* `AngularJS`
* `Angular-DataTables`

AngularJS MUST use jQuery and not its jqLite!

**Comment by narzul1** [comment]
Thanks a lot.

**Comment by narzul1** [comment]
It works but I now encounter another issues.
I'm trying to work with my data on server-side  (50k rows, only test with 100 for now).
And I get the following error :
TypeError: Unable to get property 'match' of undefined or null reference
   at render (http://localhost:52445/Scripts/angular-datatables.renderer.js:176:13)
   at Anonymous function (http://localhost:52445/Scripts/angular-datatables.directive.js:109:21)
   at wrappedCallback (http://localhost:52445/Scripts/angular.js:11575:33)
   at Anonymous function (http://localhost:52445/Scripts/angular.js:11661:25)
   at $eval (http://localhost:52445/Scripts/angular.js:12704:25)
   at $digest (http://localhost:52445/Scripts/angular.js:12516:37)
   at $apply (http://localhost:52445/Scripts/angular.js:12808:33)
   at done (http://localhost:52445/Scripts/angular.js:8379:50)
   at completeRequest (http://localhost:52445/Scripts/angular.js:8593:17)
   at onreadystatechange (http://localhost:52445/Scripts/angular.js:8532:25) 


Thanks

**Comment by l-lin** [comment]
Can you provide your HTML and JS codes?

**Comment by narzul1** [comment]
JS :  vm.dtOptions = DTOptionsBuilder.newOptions()
        .withOption('ajax', {
            url: '/api/driver/',
            type: 'GET'
        })
        .withPaginationType('full_numbers')
        .withDisplayLength(10)
        .withTableTools("//cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf")
        .withDOM('Tft<"top"l>rt<"bottom"ip><"clear">')
        .withTableToolsButtons([
                'copy',
                'print', {
                    'sExtends': 'collection',
                    'sButtonText': 'Save',
                    'aButtons': ['csv', 'xls', 'pdf'],
                    "mColumns": [0, 1, 2]
                }]);

    vm.dtColumnDefs = [
        DTColumnDefBuilder.newColumnDef(0),
        DTColumnDefBuilder.newColumnDef(1),
        DTColumnDefBuilder.newColumnDef(2),
        DTColumnDefBuilder.newColumnDef(3),
        DTColumnDefBuilder.newColumnDef(4),
        DTColumnDefBuilder.newColumnDef(5).notSortable()
    ];



html : 
"<table datatable="ng" dt-options=" drivers.dtOptions" dt-column-defs="drivers.dtColumnDefs">"

**Comment by l-lin** [comment]
Do not add the `ng` value in your `datatable` directive. If you are using the `AjaxRenderer`, then you do not need to add this value.

**Comment by narzul1** [comment]
Thanks. I have now an other issue but not from datatables.
Thanks
