### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by candidosales** [l-lin/angular-datatables#339]
When booting presents this error:
```
TypeError: $elem.hide is not a function
    at Object.showLoading (http://localhost:8000/dist/js/admin.js:59786:15)
    at postLink (http://localhost:8000/dist/js/admin.js:59058:31)
    at http://localhost:8000/dist/js/admin.js:8598:44
    at invokeLinkFn (http://localhost:8000/dist/js/admin.js:8604:9)
    at nodeLinkFn (http://localhost:8000/dist/js/admin.js:8113:11)
    at compositeLinkFn (http://localhost:8000/dist/js/admin.js:7514:13)
    at publicLinkFn (http://localhost:8000/dist/js/admin.js:7388:30)
    at compile (http://localhost:8000/dist/js/admin.js:36552:9)
    at invokeLinkFn (http://localhost:8000/dist/js/admin.js:8604:9)
    at nodeLinkFn (http://localhost:8000/dist/js/admin.js:8113:11) <table id="representante-info" datatable="" class="row-border hover ng-scope ng-isolate-scope">
```

My bower.json
```
'bower_components/angular/angular.js', // 1.4.0
                  'bower_components/angular-sanitize/angular-sanitize.js',
                  'bower_components/angular-animate/angular-animate.js',
                  'bower_components/angular-ui-router/release/angular-ui-router.js',
                  //'bower_components/jquery/dist/jquery.js',
                  'bower_components/datatables/media/js/jquery.js', //1.11.3

                  // ADMIN
                  'bower_components/bootstrap-sass/assets/javascripts/bootstrap.js',
                  'bower_components/angular-bootstrap/ui-bootstrap-tpls.js',

                  'bower_components/datatables/media/js/jquery.dataTables.js',
                  'bower_components/angular-datatables/dist/angular-datatables.js',
                  'bower_components/angular-datatables/dist/plugins/bootstrap/angular-datatables.bootstrap.js',
```

Anyone can help me?

**Comment by hjzheng** [comment]
Can you provide detail code or example on  [jsfiddle](http://jsfiddle.net) ?  So far,  I can make sure ui-bootstrap not compatible with angular 1.4, just fully test with 1.3.x.

**Comment by candidosales** [comment]
I decided,

I moved the jquery position and worked =)

```
  src: [

                  'bower_components/datatables/media/js/jquery.js',
                  'bower_components/angular/angular.js',
                  'bower_components/angular-sanitize/angular-sanitize.js',
                  'bower_components/angular-animate/angular-animate.js',
                  'bower_components/angular-ui-router/release/angular-ui-router.js',
                  //'bower_components/jquery/dist/jquery.js',


                  // ADMIN
                  'bower_components/bootstrap-sass/assets/javascripts/bootstrap.js',
                  'bower_components/angular-bootstrap/ui-bootstrap-tpls.js',

                  'bower_components/datatables/media/js/jquery.dataTables.js',
                  'bower_components/angular-datatables/dist/angular-datatables.js',
                  'bower_components/angular-datatables/dist/plugins/bootstrap/angular-datatables.bootstrap.js',

                  'bower_components/angular-input-masks/angular-input-masks.js',
                  'bower_components/angular-input-masks/angular-input-masks.br.js',

                  'bower_components/angular-datepicker/dist/index.js',

                  'bower_components/highcharts/highcharts.js',
                  'bower_components/highcharts-ng/dist/highcharts-ng.js',
                  'dev/js/admin.js'],
            dest: 'dist/js/admin.js',
```

**Comment by iscluise** [comment]
* What is Soluction ???

TypeError: $elem.hide is not a function
    at Object.showLoading (http://localhost:3000/bower_components/angular-datatables/dist/angular-datatables.js:1318:15)
    at ControllerDirective.showLoading (http://localhost:3000/bower_components/angular-datatables/dist/angular-datatables.js:496:31)
    at Object.postLink (http://localhost:3000/bower_components/angular-datatables/dist/angular-datatables.js:482:18)
    at http://localhost:3000/bower_components/angular/angular.js:1247:18
    at http://localhost:3000/bower_components/angular/angular.js:9928:44
    at invokeLinkFn (http://localhost:3000/bower_components/angular/angular.js:9934:9)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:9335:11)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8620:13)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8623:13)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8623:13) <table datatable="ng" class="table ng-isolate-scope">
